version: "3"
services:
    kali:
        build: ./Kali  
    sloth:
    
    hubris:
    
    envy:
    
    anger:
    
    greed:
    
    lust:
    
    gluttony:
    
    vigenere:
    
    rijndael:
    
    enigma:
    
    twofish:
    
    skipjack:
    
    caeser:
    
    colossus:
    
    deep blue:
    
    watson:
    